language: ruby

rvm:
  - 2.3.3

services:
  - mongodb

env:
  - MONGOID_VERSION=2
  - MONGOID_VERSION=3
  - MONGOID_VERSION=4
  - MONGOID_VERSION=5

matrix:
  allow_failures:
    - env: MONGOID_VERSION=2

cache: bundler